development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

uat:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['DATABASE_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['DATABASE_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
